### ISSUE TITLE
[Add request] clickable links from phishing mails

### ISSUE THREAD

**Issue by ceder443** [ratcode404/custom-network-blocklist#2]
**URL you wish to be added:**  
bantosamos.blogspot.com
t.yamsguchi.digital

**Why you believe this should be added:**
I recently found two phishing mails which used the two aforementioned URLs in my private e-mail spam folder.

**Comment by rat-c** [comment]
Added both, thank you!

bantosamos.blogspot.com
t.yamsguchi.digital
