### ISSUE TITLE
[Add request] domain from DHL phishing mail

### ISSUE THREAD

**Issue by ceder443** [ratcode404/custom-network-blocklist#3]
**URL you wish to be added:**
faddubfbjo.setsp03sp.club  

**Why you believe this should be added:**
This domain was found in a URL from an obvious phishing attempt. The mail used the forwarding feature from a seemingly legitimate korean website (myrealtrip.com).  
The aforementioned URL looks like this:  
`https://www.myrealtrip.com/accommodations/hotels/329587/forward?agency=BOOKING_DOT_COM&link=http://faddubfbjo.setsp03sp.club/uPihceQTQm?q=(...)`

**Comment by rat-c** [comment]
added boi
